<header class="codrops-header">
    <img style="width:120px; height: 135px;" src="{{ STATIC_URL }}qubalapp/main_engine/img/qubal_logo.png" />
	<h3 class="qubal-header-title">QUBAL SPEX <span>{{ QUBAL_VERSION }}</span>
		<span>
			<a href='{{ SUNRISE_URL }}admin' class='btn btn-min btn-warning'><i class='icon-cog'></i>&nbsp;ADMIN</a>
		</span>
		<span>
			<a href='{{ SUNRISE_URL }}logout' class='btn btn-min btn-inverse'><i class='icon-signout'></i>&nbsp;LOGOUT</a>
		</span>
	</h3>
</header>