<div id="st-container" class="st-container">
    <nav class="st-menu st-effect-11" id="menu-11">
        <h2 class="iconcodec icon-sitemap"><div class='sidemenu-text'>QUBAL SPEX</div></h2>
        <ul>
          <li><a class="iconcodec icon-dashboard" href="{{ SUNRISE_URL }}spex_/"><div class='sidemenu-text'>Dashboard</div></a></li>
          <li><a class="iconcodec icon-user" href="{{ SUNRISE_URL }}spex_/profile/"><div class='sidemenu-text'>Profile</div></a></li>
          <li><a class="iconcodec icon-group" href="{{ SUNRISE_URL }}spex_/teams/"><div class='sidemenu-text'>Teams</div></a></li>
          <li><a class="iconcodec icon-tasks" href="{{ SUNRISE_URL }}spex_/courses/"><div class='sidemenu-text'>Courses</div></a></li>
          <li><a class="iconcodec icon-shield" href="{{ SUNRISE_URL }}spex_/quests/"><div class='sidemenu-text'>Quests</div></a></li>
          <li><a class="iconcodec icon-inbox" href="#"><div class='sidemenu-text'>Inbox</div></a></li>
          <li><a class="iconcodec icon-keyboard" href="#"><div class='sidemenu-text'>Notes</div></a></li>
        </ul>

        <h5 class='version-text'>{{ QUBAL_VERSION }}</h5>

    </nav>
      <!-- content push wrapper -->
    <div class="st-pusher">
    <!--  
      example menus 
      these menus will be under the push wrapper
    -->

        


        <div class="st-content"><!-- this is the wrapper for the content -->
            <div class="st-content-inner"><!-- extra div for emulating position:fixed of the menu -->

                <!-- Top Navigation -->
                <div class="codrops-top clearfix">
                    <span class="right"><a href="{{ SUNRISE_URL }}"><span class='OpenSans-Light student-name'><i class="icon-beer"></i>&nbsp;&nbsp;Original taste</span></a></span>
                    <span class="right"><a href="{{ SUNRISE_URL }}jawa_/"><span class='OpenSans-Light student-name'><i class="icon-renren"></i>&nbsp;&nbsp;Jawa flavour</span></a></span>
                </div> 
                
                <div id="st-trigger-effects" class="">
                    <button data-effect="st-effect-11">menu</button>
                </div>